#!/usr/bin/env bash
#Displays the time for 12hours and 59minutes

i=0

while [ $i -lt 13 ];
do
        j=1
echo "Hour: $i"

while [ $j -lt 60 ];
do
        echo "$j"
        ((j++))
done

((i++))
done
