#!/usr/bin/env bash
#This script gives information about the school file

fl="school"

if [[ -e "$fl" ]];
then
        echo "$fl file exists"

        if [[ -s "$fl" ]];
        then
                echo "$fl file is not  empty"
        else
                echo "$fl file is empty"
        fi

        if [[ -f "$fl" ]];
        then
                echo "$fl is a regular file"
        fi
else
        echo "$fl file doesn't exist"
fi
